#53 unit test routes
stiftelsen-effekt/effekt-backend pull request #324
Opened 2022-03-16 08:02 UTC by livejsa

Added a test for endpoint /:id/donations in donors.ts

2022-03-16 11:17 UTC, fellmirr requested changes

2022-03-16 11:17 UTC, fellmirr commented on src/__test__/donors.js
> +    donationStub.withArgs("237").resolves(donation);
Bør returnere et array med donasjoner, ikke en enkelt donasjon

2022-03-16 11:17 UTC, fellmirr commented on src/__test__/donors.js
> +    expect(response.body.content).to.deep.equal(donation);
Her også, bør sjekke at det er et array med donasjoner, ikke en enkelt donasjon

2022-03-16 12:36 UTC, livejsa commented on src/__test__/donors.js
> +    donationStub.withArgs("237").resolves(donation);
Har lagt til enda en donasjon nå :)

2022-03-17 09:42 UTC, fellmirr approved these changes
Good stuff :+1:

2022-03-17 09:43 UTC, merged