Faceb import
stiftelsen-effekt/effekt-backend pull request #385
Opened 2022-08-03 12:43 UTC by henmyhre

Added functionality to upload and register facebook donations. See https://github.com/stiftelsen-effekt/effekt-admin/pull/226 for more info.

2022-08-03 20:11 UTC, philiphand commented on src/routes/facebook.ts
> +router.get("/payments/all", async (req, res, next) => {
Mangler authorization?

2022-08-03 20:13 UTC, philiphand requested changes
Ser bra ut! Men ser ut som den ene routen mangler auth

2022-08-04 13:24 UTC, fellmirr requested changes
Looking very snazzy, only one small question :)

2022-08-05 07:51 UTC, fellmirr commented on src/routes/facebook.ts
> +      await mail.sendFacebookTaxConfirmation(email, full_name, paymentID);
Misunderstanding, used by the tax form

2022-08-05 07:51 UTC, merged