Adds fb token negotiation and adds (temporary) code for posting exter…
stiftelsen-effekt/effekt-backend pull request #460
Opened 2022-11-16 13:23 UTC by fellmirr

…nal donations to fb

Closes #455 

For some reason all of the schema types were updated when generating the schema, not sure why, does not seem to be important

2022-11-18 09:35 UTC, fellmirr commented on src/routes/facebook.ts
> +// Route to get token
This needs to go!

2022-11-18 12:42 UTC, EliseAndresen commented on src/custom_modules/facebook.ts
> +  console.log(config.facebook_sync_app_id, config.facebook_sync_app_secret);
console.log

2022-11-18 12:51 UTC, EliseAndresen requested changes
Good to go når kode snutten i src/routes/facebook.ts er slettet

2022-11-18 15:08 UTC, EliseAndresen approved these changes

2022-11-22 13:23 UTC, fellmirr commented on src/custom_modules/facebook.ts
> +  console.log(config.facebook_sync_app_id, config.facebook_sync_app_secret);
Done

2022-11-22 13:26 UTC, merged